### ISSUE TITLE
Can't get it to work in Safari, Chrome or web pop-up

### ISSUE THREAD

**Issue by Younghart** [ttscoff/cheaters#23]
Hi,

First of all, I love the concept! Im thinking about combining it with either [Fluid](http://fluidapp.com) or [Fluid Browser](http://fluidbrowser.com). I stumbled upon cheaters in your "[Rest of the Best](http://brettterpstra.com/2016/02/26/a-look-back-at-2015-the-rest-of-the-best/)" blog post. 

But I can't seem to be able to open cheat.html (or index-example.html) properly. The menu bar apprears (Safari/Chrome, not web pop-up), as well as JavaScript elements such as fast switch and color inverter. But from the content, only the CSS3 category loads, which is an image.

Firefox, on the other hand, has no problem loading the whole content. 

Any ideas what might go wrong? Is that a sandbox thing, disallowing the browser to load other html files from the hard drive? And if so: how do I grant permissions?

Kind regards,

Immo

**Comment by Younghart** [comment]
By the way: If you save your Automator workflow as a service, you can assign a keyboard shortcut in System Preferences/Keyboard/Shortcuts/Services. That way, you don't need an additional helper such as Keyboard Maestro.

**Comment by ttscoff** [comment]
It's really designed to be used in Fluid only, and via local webserver 
(OS X built-in web sharing works fine), not directly from a file. Webkit 
browsers block local scripts from loading as a security measure, and 
it's a pain to try and work around that.

-Brett

**Comment by Younghart** [comment]
Ah, I see. Thanks for clearing that up! I already own Fluid, so nothing will stand between me and my personal [BetterTouchTool](https://www.boastr.net) cheat sheet! Maniacal laugh.
