### ISSUE TITLE
Fluidapp v.2 or Chrome or Safari would not load any cheatsheets

### ISSUE THREAD

**Issue by ruslaniv** [ttscoff/cheaters#27]
I'm not able to load any cheatsheets either in Fluidapp 2.1 or in latest Chrome or Safari. It only loads the `<li>` elements, but clicking on any of them does not open the corresponding cheatsheet. 
I double checked the paths and toggled "Allow browsing to any URL" but still, no luck. 
But strangely enough, it works if I open the file in Firefox.
![screenshot 2018-10-18 at 10 53 15](https://user-images.githubusercontent.com/7631314/47133909-2a4e5600-d2c4-11e8-8f6f-aee961c8e861.png)

**Comment by ruslaniv** [comment]
Just found an old version of Fluidapp (Version 1.8.6 (2331)) and Cheaters 2.1.2 still works in the old version.

**Comment by ruslaniv** [comment]
@alpayne 
Somehow I missed the section in readme about the local web server. Set up apache and it works just fine now. Although still wondering why it worked in older version of fluidapp without the need of a web server.

**Comment by alpayne** [comment]
Seems Fluid didn't enforce CORS previously.
