### ISSUE TITLE
Inline HTML in markdown document

### ISSUE THREAD

**Issue by artoric** [ttscoff/cheaters#28]
Hi Brett and thank you for the Cheaters!
I'm trying to add some inline HTML to the markdown document; unfortunately, marked.js skips it all of them.

```html
<div style="leftCol">
markdown content
</div>
```

My cheaters.js:

```javascript
$('#container').html(
  marked(mdText, {
    smartLists: true,
    breaks: true,
    tables: true,
    gfm: true,
    sanitize: false,
    pedantic: true
  })
);
```

Any idea what happens here? -Thank you!

**Comment by ttscoff** [comment]
Haven't played with this in marked.js for a long time, but it sounds 
like something particular to that JS library? I'd have to dig in deeper 
than I have time for right now…

-Brett

**Comment by artoric** [comment]
Yes, probably something with the marked.js. -Anyway, this serves my needs:

```
.replace(/---div/g,'<div')
.replace(/;;;div/g,'</div>')
```
Thanks!
